name: Build

on: push
jobs:
  build-nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.TOKEN }}
    - run: nix build
    - run: nix flake check
    - run: nix flake info
    - run: nix flake show --all-systems
